SCREEN_WIDTH = 650
SCREEN_HEIGHT = 650
DEFAULT_OBJ_SIZE = 50

FRAMES_PER_SECOND = 60
DEFAULT_PLAYER_HP = 100
DEFAULT_PLAYER_SPEED = 5
DEFAULT_ENEMIES_SPEED = 2
BOMB_TIMER = 3
BOMB_EXPLODE_RANGE = 5
BACKGROUND_COLOR = (0, 0, 0)
DEFAULT_EVENT_TIMEOUT = 1
