import pygame


SCREEN_WIDTH = 650
SCREEN_HEIGHT = 650
BACKGROUND_COLOR = (0, 0, 0)
FRAMES_PER_SECOND = 60

DEFAULT_OBJ_SIZE = 50
DEFAULT_PLAYER_HP = 100
DEFAULT_SCORE_INCREASE = 10

DEFAULT_PLAYER_SPEED = 4

BOMB_TIMER = 90
BOMB_COOLDOWN = 45
EXPLOSION_RANGE = 2

ADDENEMY = pygame.USEREVENT + 1
DEFAULT_EVENT_TIMEOUT = 3000
